"""
payroll_fields.py
=================
Field specification for Brutto-Netto-Abrechnung (German payroll document).

Each field has precise x0/top/x1/bottom coordinates in PDF points
(pdfplumber convention: y=0 at page top).
Generated from Lohnabrechnung_Felder_mit_Koordinaten.xlsx.
"""

import os
import sys

# ── Template paths ────────────────────────────────────────────────────────────

_HERE = os.path.dirname(os.path.abspath(__file__))
# When running as a PyInstaller bundle, use _MEIPASS as root
if getattr(sys, 'frozen', False):
    _ROOT = sys._MEIPASS
else:
    _ROOT = os.path.dirname(os.path.dirname(_HERE))

TEMPLATE_BLANK_PDF = os.path.join(_ROOT, "files", "blank template.pdf")
TEMPLATE_PDF = os.path.join(_ROOT, "pdf_editor", "templates",
                            "2025-12 Abrechnungen Brutto-Netto (1).pdf")

# ── Field Specification ─────────────────────────────────────────────────────
#
# Each entry:
#   id            - unique identifier
#   label         - display name
#   section       - logical section in the document
#   default_value - value from the reference filled PDF
#   x0, top       - anchor point (PDF pt, y=0 at top)
#   x1, bottom    - bounding box right/lower edge
#   alignment     - "left" or "right"
#   type          - "text", "number", "date", "iban", "bic"
#
# Text MUST stay within [x0,x1] horizontally and [top,bottom] vertically.

FIELD_SPEC: list[dict] = [

    # ── HEADER ────────────────────────────────────────────────────────

    {
        "id": "abrechnungsmonat",
        "label": "Abrechnungsmonat",
        "section": "HEADER",
        "default_value": "",
        "x0": 365.19, "top": 21.55,
        "x1": 470.00, "bottom": 30.53,
        "alignment": "left",
        "type": "text",
        "font_name": "Arial-BoldMT",
        "font_size": 8.9858,
    },
    {
        "id": "korrektur_abrechnung",
        "label": "Korrektur-Abrechnung",
        "section": "HEADER",
        "default_value": "",
        "x0": 365.19, "top": 31.47,
        "x1": 520.00, "bottom": 40.45,
        "alignment": "left",
        "type": "text",
        "font_name": "Arial-BoldMT",
        "font_size": 8.9858,
        "placeholder": "z.B. Korrektur-Abrechnung",
    },
    {
        "id": "seite_aktuell",
        "label": "Seite (aktuell)",
        "section": "HEADER",
        "default_value": "1",
        "x0": 552.91, "top": 21.55,
        "x1": 557.91, "bottom": 30.53,
        "alignment": "left",
        "type": "text",
        "font_name": "Arial-BoldMT",
        "font_size": 8.9858,
    },
    {
        "id": "seite_slash",
        "label": "/ (Trenner)",
        "section": "HEADER",
        "default_value": "/",
        "x0": 560.40, "top": 21.55,
        "x1": 562.90, "bottom": 30.53,
        "alignment": "left",
        "type": "text",
        "font_name": "Arial-BoldMT",
        "font_size": 8.9858,
        "editable": False,
    },
    {
        "id": "seite_gesamt",
        "label": "Seite (gesamt)",
        "section": "HEADER",
        "default_value": "31",
        "x0": 565.40, "top": 21.55,
        "x1": 575.39, "bottom": 30.53,
        "alignment": "left",
        "type": "text",
        "font_name": "Arial-BoldMT",
        "font_size": 8.9858,
    },
    {
        "id": "blatt_nummer",
        "label": "Blatt",
        "section": "HEADER",
        "default_value": "1",
        "x0": 570.40, "top": 31.47,
        "x1": 575.39, "bottom": 40.45,
        "alignment": "left",
        "type": "text",
        "font_name": "Arial-BoldMT",
        "font_size": 8.9858,
    },
    {
        "id": "korrektur_subtitle",
        "label": "Korrektur-Untertitel",
        "section": "HEADER",
        "default_value": "",
        "x0": 358.44, "top": 31.47,
        "x1": 450.0, "bottom": 40.46,
        "alignment": "center",
        "type": "text",
        "editable": False,
    },

    # ── PERSÖNLICHE DATEN ─────────────────────────────────────────────

    {
        "id": "pers_nr",
        "label": "Pers.-Nr.",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "xxxxx",
        "x0": 58.34, "top": 53.15,
        "x1": 80.56, "bottom": 61.14,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "steuer_id",
        "label": "Steuer-ID",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "xxxxxxxxxxx",
        "x0": 98.84, "top": 53.15,
        "x1": 147.73, "bottom": 61.14,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "geburtsdatum",
        "label": "Geburtsdatum",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "xx.xx.xxxx",
        "x0": 171.32, "top": 53.15,
        "x1": 211.31, "bottom": 61.14,
        "alignment": "left",
        "type": "date",
    },
    {
        "id": "eintritt",
        "label": "Eintritt",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "xx.xx.xxxx",
        "x0": 230.84, "top": 53.15,
        "x1": 270.84, "bottom": 61.14,
        "alignment": "left",
        "type": "date",
    },
    {
        "id": "austritt",
        "label": "Austritt",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "",
        "x0": 284.71, "top": 53.15,
        "x1": 324.71, "bottom": 61.14,
        "alignment": "left",
        "type": "date",
    },
    {
        "id": "st_kl_steuerklasse",
        "label": "St.Kl. (Steuerklasse)",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "1",
        "x0": 337.9, "top": 53.15,
        "x1": 342.34, "bottom": 61.14,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "faktor",
        "label": "Faktor",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "",
        "x0": 358.59, "top": 53.15,
        "x1": 375.54, "bottom": 61.14,
        "alignment": "left",
        "type": "number",
    },
    {
        "id": "kinder_fb",
        "label": "Kinder-FB",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "0,0",
        "x0": 394.1, "top": 53.15,
        "x1": 405.21, "bottom": 61.14,
        "alignment": "left",
        "type": "number",
    },
    {
        "id": "st_tg_steuertage",
        "label": "St.Tg. (Steuertage)",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "30",
        "x0": 419.3, "top": 53.15,
        "x1": 428.19, "bottom": 61.14,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "freibetrag_jaehrl",
        "label": "Freibetrag jährl.",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "",
        "x0": 438.23, "top": 53.15,
        "x1": 465.0, "bottom": 61.14,
        "alignment": "left",
        "type": "number",
    },
    {
        "id": "freibetrag_mtl",
        "label": "Freibetrag mtl.",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "",
        "x0": 490.92, "top": 53.15,
        "x1": 518.0, "bottom": 61.14,
        "alignment": "left",
        "type": "number",
    },
    {
        "id": "konfession",
        "label": "Konfession",
        "section": "PERSÖNLICHE DATEN",
        "default_value": "/",
        "x0": 540.75, "top": 53.15,
        "x1": 570.34, "bottom": 61.14,
        "alignment": "center",
        "type": "text",
    },

    # ── SOZIALVERSICHERUNG ────────────────────────────────────────────

    {
        "id": "versicherungs_nr",
        "label": "Versicherungs-Nr.",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "xxxxxxxxxxxxxx",
        "x0": 65.0, "top": 71.28,
        "x1": 119.22, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "krankenkassenname",
        "label": "Krankenkassenname",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "AOK Nordost",
        "x0": 136.06, "top": 71.28,
        "x1": 300.00, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "kk_pct",
        "label": "KK%",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "14,60",
        "x0": 369.72, "top": 71.28,
        "x1": 389.72, "bottom": 79.28,
        "alignment": "left",
        "type": "number",
    },
    {
        "id": "kk_z_slash",
        "label": "KK/Z Trenner",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "/",
        "x0": 391.46, "top": 71.28,
        "x1": 393.69, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
        "editable": False,
    },
    {
        "id": "z_pct",
        "label": "Z%",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "3,50",
        "x0": 395.41, "top": 71.28,
        "x1": 410.96, "bottom": 79.28,
        "alignment": "left",
        "type": "number",
    },
    {
        "id": "p",
        "label": "P",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "1",
        "x0": 429.02, "top": 71.28,
        "x1": 433.47, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "g",
        "label": "G",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "0",
        "x0": 435.69, "top": 71.28,
        "x1": 440.13, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "s",
        "label": "S",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "1",
        "x0": 442.35, "top": 71.28,
        "x1": 446.8, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "um",
        "label": "UM",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "2",
        "x0": 454.11, "top": 71.28,
        "x1": 458.55, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "mfb",
        "label": "MFB",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "Nein",
        "x0": 467.96, "top": 71.28,
        "x1": 484.4, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "ueb",
        "label": "ÜB",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "1",
        "x0": 493.79, "top": 71.28,
        "x1": 498.23, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "b",
        "label": "B",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "1",
        "x0": 505.07, "top": 71.28,
        "x1": 509.51, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "g_sv",
        "label": "G (SV)",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "1",
        "x0": 511.73, "top": 71.28,
        "x1": 516.18, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "r",
        "label": "R",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "1",
        "x0": 518.4, "top": 71.28,
        "x1": 522.84, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "s_sv",
        "label": "S (SV)",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "1",
        "x0": 525.06, "top": 71.28,
        "x1": 529.51, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "sv_tg",
        "label": "SV.Tg.",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "30",
        "x0": 536.92, "top": 71.28,
        "x1": 545.81, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "anz_u",
        "label": "Anz.U.",
        "section": "SOZIALVERSICHERUNG",
        "default_value": "",
        "x0": 553.65, "top": 71.28,
        "x1": 571.6, "bottom": 79.28,
        "alignment": "left",
        "type": "text",
    },

    # ── STATISTISCHE WERTE ────────────────────────────────────────────

    {
        "id": "anw_std",
        "label": "Anw.-Std.",
        "section": "STATISTISCHE WERTE",
        "default_value": "43,33",
        "x0": 362.64, "top": 120.6,
        "x1": 382.64, "bottom": 128.6,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "sv_ag_anteil_mtl",
        "label": "SV-AG-Anteil mtl.",
        "section": "STATISTISCHE WERTE",
        "default_value": "1.451,41-",
        "x0": 535.93, "top": 120.6,
        "x1": 569.7, "bottom": 128.6,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "anw_tage",
        "label": "Anw.-Tage",
        "section": "STATISTISCHE WERTE",
        "default_value": "21,67",
        "x0": 362.64, "top": 138.74,
        "x1": 382.64, "bottom": 146.74,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "sv_ag_anteil_kum",
        "label": "SV-AG-Anteil kum.",
        "section": "STATISTISCHE WERTE",
        "default_value": "14.428,66-",
        "x0": 531.51, "top": 138.74,
        "x1": 569.73, "bottom": 146.74,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "durchschnitt_1",
        "label": "Durchschnitt 1",
        "section": "STATISTISCHE WERTE",
        "default_value": "221,14",
        "x0": 358.19, "top": 175.02,
        "x1": 382.63, "bottom": 183.02,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "durchschnitt_2",
        "label": "Durchschnitt 2",
        "section": "STATISTISCHE WERTE",
        "default_value": "221,14",
        "x0": 400.7, "top": 175.02,
        "x1": 425.15, "bottom": 183.02,
        "alignment": "right",
        "type": "number",
    },

    # ── STATISTISCHE WERTE – Row 2 value slots ───────────────────────

    {
        "id": "ueber_std",
        "label": "Über.-Std.",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 397.90, "top": 120.6,
        "x1": 425.15, "bottom": 128.6,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "bez_std_n_gel",
        "label": "Bez.Std.n.gel.",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 430.64, "top": 120.6,
        "x1": 467.87, "bottom": 128.6,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "url_anspr",
        "label": "Url.-Anspr.",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 481.63, "top": 120.6,
        "x1": 510.20, "bottom": 128.6,
        "alignment": "right",
        "type": "number",
    },

    # ── STATISTISCHE WERTE – Row 3 value slots ───────────────────────

    {
        "id": "fehl_tage",
        "label": "Fehl.-Tage",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 396.26, "top": 138.74,
        "x1": 425.17, "bottom": 146.74,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "krh_tage",
        "label": "Krh.-Tage",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 441.10, "top": 138.74,
        "x1": 467.68, "bottom": 146.74,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "url_vorj",
        "label": "Url. Vorj.",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 486.93, "top": 138.74,
        "x1": 510.18, "bottom": 146.74,
        "alignment": "right",
        "type": "number",
    },

    # ── STATISTISCHE WERTE – Row 4 value slots (Std.-Lohn) ──────────

    {
        "id": "std_lohn_1",
        "label": "Std.-Lohn 1",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 351.73, "top": 156.88,
        "x1": 382.65, "bottom": 164.88,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "std_lohn_2",
        "label": "Std.-Lohn 2",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 394.24, "top": 156.88,
        "x1": 425.16, "bottom": 164.88,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "std_lohn_3",
        "label": "Std.-Lohn 3",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 436.76, "top": 156.88,
        "x1": 467.68, "bottom": 164.88,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "gen_url_ges",
        "label": "gen. Url. ges.",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 474.62, "top": 156.88,
        "x1": 510.19, "bottom": 164.88,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "arbeitszeitkonto_std",
        "label": "Arbeitszeitkonto (Std.)",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 514.79, "top": 156.88,
        "x1": 569.70, "bottom": 164.88,
        "alignment": "right",
        "type": "number",
    },

    # ── STATISTISCHE WERTE – Row 5 value slots ──────────────────────

    {
        "id": "grundlohn",
        "label": "Grundlohn",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 439.76, "top": 175.02,
        "x1": 467.69, "bottom": 183.02,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "resturlaub",
        "label": "Resturlaub",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 481.29, "top": 175.02,
        "x1": 510.20, "bottom": 183.02,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "arbeitszeitkonto_betr",
        "label": "Arbeitszeitkonto (Betr.)",
        "section": "STATISTISCHE WERTE",
        "default_value": "",
        "x0": 513.80, "top": 175.02,
        "x1": 569.70, "bottom": 183.02,
        "alignment": "right",
        "type": "number",
    },

    # ── EMPFÄNGERADRESSE ──────────────────────────────────────────────

    {
        "id": "p_nr",
        "label": "*P.-Nr.",
        "section": "EMPFÄNGERADRESSE",
        "default_value": "xxx*",
        "x0": 93.55, "top": 181.55,
        "x1": 105.85, "bottom": 187.53,
        "alignment": "left",
        "type": "text",
        "font_size": 5.98,
    },
    {
        "id": "anrede",
        "label": "Anrede",
        "section": "EMPFÄNGERADRESSE",
        "default_value": "xxxxx",
        "x0": 72.29, "top": 190.33,
        "x1": 92.27, "bottom": 198.32,
        "alignment": "left",
        "type": "text",
        "no_length_check": True,
    },
    {
        "id": "vorname_nachname",
        "label": "Vorname + Nachname",
        "section": "EMPFÄNGERADRESSE",
        "default_value": "xxxxxxx xxxxxxxxxxx",
        "x0": 72.29, "top": 200.25,
        "x1": 143.35, "bottom": 208.24,
        "alignment": "left",
        "type": "text",
        "no_length_check": True,
    },
    {
        "id": "strasse_hausnummer",
        "label": "Straße + Hausnummer",
        "section": "EMPFÄNGERADRESSE",
        "default_value": "xxxxxxxxx xxxxxx xxx",
        "x0": 72.29, "top": 210.17,
        "x1": 152.69, "bottom": 218.16,
        "alignment": "left",
        "type": "text",
        "no_length_check": True,
    },
    {
        "id": "plz_ort",
        "label": "PLZ + Ort",
        "section": "EMPFÄNGERADRESSE",
        "default_value": "xxxxx xxxxxx",
        "x0": 72.29, "top": 220.09,
        "x1": 117.16, "bottom": 228.08,
        "alignment": "left",
        "type": "text",
        "no_length_check": True,
    },

    # ── ARBEITGEBER ──────────────────────────────────────────────────

    {
        "id": "arbeitgeber_name",
        "label": "Arbeitgeber",
        "section": "ARBEITGEBER",
        "default_value": "",
        "x0": 72.29, "top": 135.5,
        "x1": 288.22, "bottom": 143.5,
        "alignment": "left",
        "type": "text",
        "font_size": 5.98,
        "wrap": True,
    },

    # ── KALENDER ─────────────────────────────────────────────────────

    {
        "id": "kw_zeile_1",
        "label": "KW Zeile 1",
        "section": "KALENDER",
        "default_value": "",
        "x0": 345.83, "top": 225.50,
        "x1": 360.00, "bottom": 233.49,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "kw_zeile_2",
        "label": "KW Zeile 2",
        "section": "KALENDER",
        "default_value": "",
        "x0": 345.83, "top": 243.64,
        "x1": 360.00, "bottom": 251.63,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "kw_zeile_3",
        "label": "KW Zeile 3",
        "section": "KALENDER",
        "default_value": "",
        "x0": 345.83, "top": 261.78,
        "x1": 360.00, "bottom": 269.77,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "kw_zeile_4",
        "label": "KW Zeile 4",
        "section": "KALENDER",
        "default_value": "",
        "x0": 345.83, "top": 279.92,
        "x1": 360.00, "bottom": 287.91,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "kw_zeile_5",
        "label": "KW Zeile 5",
        "section": "KALENDER",
        "default_value": "",
        "x0": 345.83, "top": 298.06,
        "x1": 360.00, "bottom": 306.05,
        "alignment": "left",
        "type": "text",
    },

    # ── LOHNARTEN-TABELLE ─────────────────────────────────────────────

    # Mask the blank template's embedded row-1 text ("L L J" at x=376,398,422)
    # which differs from the overlay field positions and would bleed through.
    # Split into per-cell masks to avoid covering vertical column divider
    # lines at x=277.78, 331.63, 371.31, 419.50.
    {
        "id": "_lohnart_row1_mask_bez",
        "label": "Lohnart Row 1 Mask (Bezeichnung)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 110.0, "top": 359.0,
        "x1": 277.0, "bottom": 370.0,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "_lohnart_row1_mask_menge",
        "label": "Lohnart Row 1 Mask (Menge)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 279.0, "top": 359.0,
        "x1": 331.0, "bottom": 370.0,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "_lohnart_row1_mask_faktor",
        "label": "Lohnart Row 1 Mask (Faktor)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 333.0, "top": 359.0,
        "x1": 370.0, "bottom": 370.0,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "_lohnart_row1_mask_zuschlag",
        "label": "Lohnart Row 1 Mask (Zuschlag)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 373.0, "top": 359.0,
        "x1": 418.0, "bottom": 370.0,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "_lohnart_row1_mask_st",
        "label": "Lohnart Row 1 Mask (St)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 421.0, "top": 359.0,
        "x1": 441.0, "bottom": 370.0,
        "alignment": "left",
        "type": "text",
    },

    {
        "id": "lohnart",
        "label": "Lohnart",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "0005",
        "x0": 58.42, "top": 361.24,
        "x1": 76.2, "bottom": 369.24,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "bezeichnung",
        "label": "Bezeichnung",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "Gehalt",
        "x0": 86.46, "top": 361.24,
        "x1": 110.0, "bottom": 369.24,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "st",
        "label": "St *)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "L",
        "x0": 428.6, "top": 361.24,
        "x1": 433.04, "bottom": 369.24,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "sv",
        "label": "SV *)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "L",
        "x0": 452.69, "top": 361.24,
        "x1": 457.13, "bottom": 369.24,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "gb",
        "label": "GB *)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "J",
        "x0": 478.42, "top": 361.24,
        "x1": 482.42, "bottom": 369.24,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "betrag_lohnart",
        "label": "Betrag (Lohnart)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "9.582,19",
        "x0": 536.38, "top": 361.24,
        "x1": 567.49, "bottom": 369.24,
        "alignment": "right",
        "type": "number",
    },
    # Row 1 extra columns
    {
        "id": "menge_row1",
        "label": "Menge (Zeile 1)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 305.0, "top": 361.24,
        "x1": 330.0, "bottom": 369.24,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "faktor_pct_row1",
        "label": "Faktor/%/€-Zuschlag (Zeile 1)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 346.0, "top": 361.24,
        "x1": 370.0, "bottom": 369.24,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "pct_zuschlag_row1",
        "label": "% / €-Zuschlag (Zeile 1)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 394.0, "top": 361.24,
        "x1": 418.0, "bottom": 369.24,
        "alignment": "right",
        "type": "number",
    },

    # ── Row 2 ──
    {
        "id": "lohnart_row2",
        "label": "Lohnart (Zeile 2)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 58.42, "top": 370.31,
        "x1": 76.2, "bottom": 378.31,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "bezeichnung_row2",
        "label": "Bezeichnung (Zeile 2)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 86.46, "top": 370.31,
        "x1": 160.0, "bottom": 378.31,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "menge_row2",
        "label": "Menge (Zeile 2)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 305.0, "top": 370.31,
        "x1": 330.0, "bottom": 378.31,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "faktor_pct_row2",
        "label": "Faktor/%/€-Zuschlag (Zeile 2)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 346.0, "top": 370.31,
        "x1": 370.0, "bottom": 378.31,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "pct_zuschlag_row2",
        "label": "% / €-Zuschlag (Zeile 2)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 394.0, "top": 370.31,
        "x1": 418.0, "bottom": 378.31,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "st_row2",
        "label": "St *) (Zeile 2)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 428.6, "top": 370.31,
        "x1": 433.04, "bottom": 378.31,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "sv_row2",
        "label": "SV *) (Zeile 2)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 452.69, "top": 370.31,
        "x1": 457.13, "bottom": 378.31,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "gb_row2",
        "label": "GB *) (Zeile 2)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 478.42, "top": 370.31,
        "x1": 482.42, "bottom": 378.31,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "betrag_row2",
        "label": "Betrag (Zeile 2)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 536.38, "top": 370.31,
        "x1": 567.49, "bottom": 378.31,
        "alignment": "right",
        "type": "number",
    },

    # ── Row 3 ──
    {
        "id": "lohnart_row3",
        "label": "Lohnart (Zeile 3)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 58.42, "top": 379.38,
        "x1": 76.2, "bottom": 387.38,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "bezeichnung_row3",
        "label": "Bezeichnung (Zeile 3)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 86.46, "top": 379.38,
        "x1": 200.0, "bottom": 387.38,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "menge_row3",
        "label": "Menge (Zeile 3)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 305.0, "top": 379.38,
        "x1": 330.0, "bottom": 387.38,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "faktor_pct_row3",
        "label": "Faktor/%/€-Zuschlag (Zeile 3)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 346.0, "top": 379.38,
        "x1": 370.0, "bottom": 387.38,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "pct_zuschlag_row3",
        "label": "% / €-Zuschlag (Zeile 3)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 394.0, "top": 379.38,
        "x1": 418.0, "bottom": 387.38,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "st_row3",
        "label": "St *) (Zeile 3)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 428.6, "top": 379.38,
        "x1": 433.04, "bottom": 387.38,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "sv_row3",
        "label": "SV *) (Zeile 3)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 452.69, "top": 379.38,
        "x1": 457.13, "bottom": 387.38,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "gb_row3",
        "label": "GB *) (Zeile 3)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 478.42, "top": 379.38,
        "x1": 482.42, "bottom": 387.38,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "betrag_row3",
        "label": "Betrag (Zeile 3)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 536.38, "top": 379.38,
        "x1": 567.49, "bottom": 387.38,
        "alignment": "right",
        "type": "number",
    },

    # ── Row 4 ──
    {
        "id": "lohnart_row4",
        "label": "Lohnart (Zeile 4)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 58.42, "top": 388.45,
        "x1": 76.2, "bottom": 396.45,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "bezeichnung_row4",
        "label": "Bezeichnung (Zeile 4)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 86.46, "top": 388.45,
        "x1": 200.0, "bottom": 396.45,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "menge_row4",
        "label": "Menge (Zeile 4)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 305.0, "top": 388.45,
        "x1": 330.0, "bottom": 396.45,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "faktor_pct_row4",
        "label": "Faktor/%/€-Zuschlag (Zeile 4)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 346.0, "top": 388.45,
        "x1": 370.0, "bottom": 396.45,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "pct_zuschlag_row4",
        "label": "% / €-Zuschlag (Zeile 4)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 394.0, "top": 388.45,
        "x1": 418.0, "bottom": 396.45,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "st_row4",
        "label": "St *) (Zeile 4)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 428.6, "top": 388.45,
        "x1": 433.04, "bottom": 396.45,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "sv_row4",
        "label": "SV *) (Zeile 4)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 452.69, "top": 388.45,
        "x1": 457.13, "bottom": 396.45,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "gb_row4",
        "label": "GB *) (Zeile 4)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 478.42, "top": 388.45,
        "x1": 482.42, "bottom": 396.45,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "betrag_row4",
        "label": "Betrag (Zeile 4)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 536.38, "top": 388.45,
        "x1": 567.49, "bottom": 396.45,
        "alignment": "right",
        "type": "number",
    },

    # ── Row 5 (often P40A / PauschBr.) ──
    {
        "id": "lohnart_row5",
        "label": "Lohnart (Zeile 5)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 57.5, "top": 397.52,
        "x1": 77.1, "bottom": 405.52,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "bezeichnung_row5",
        "label": "Bezeichnung (Zeile 5)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 86.46, "top": 397.52,
        "x1": 200.0, "bottom": 405.52,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "menge_row5",
        "label": "Menge (Zeile 5)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 305.0, "top": 397.52,
        "x1": 330.0, "bottom": 405.52,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "faktor_pct_row5",
        "label": "Faktor/%/€-Zuschlag (Zeile 5)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 346.0, "top": 397.52,
        "x1": 370.0, "bottom": 405.52,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "pct_zuschlag_row5",
        "label": "% / €-Zuschlag (Zeile 5)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 394.0, "top": 397.52,
        "x1": 418.0, "bottom": 405.52,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "st_row5",
        "label": "St *) (Zeile 5)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 428.6, "top": 397.52,
        "x1": 433.04, "bottom": 405.52,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "sv_row5",
        "label": "SV *) (Zeile 5)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 452.69, "top": 397.52,
        "x1": 457.13, "bottom": 405.52,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "gb_row5",
        "label": "GB *) (Zeile 5)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 478.42, "top": 397.52,
        "x1": 482.42, "bottom": 405.52,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "betrag_row5",
        "label": "Betrag (Zeile 5)",
        "section": "LOHNARTEN-TABELLE",
        "default_value": "",
        "x0": 536.38, "top": 397.52,
        "x1": 567.49, "bottom": 405.52,
        "alignment": "right",
        "type": "number",
    },

    # ── STEUER-ABRECHNUNG ─────────────────────────────────────────────

    {
        "id": "abrechnungs_brutto",
        "label": "Abrechnungs-Brutto",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "9.582,19",
        "x0": 536.39, "top": 534.14,
        "x1": 567.49, "bottom": 542.13,
        "alignment": "right",
        "type": "number",
    },
    # Tax row labels (6.97pt font)
    {
        "id": "lst_label",
        "label": "LSt (Zeile)",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "",
        "x0": 59.53, "top": 552.15,
        "x1": 70.00, "bottom": 559.12,
        "alignment": "left",
        "type": "text",
        "font_size": 6.97,
        "editable": False,
    },
    {
        "id": "lst_st_brutto_lfd_l",
        "label": "LSt – St.-Brutto lfd. (L)",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "9.582,19",
        "x0": 116.9, "top": 552.28,
        "x1": 148.01, "bottom": 560.27,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "lst_st_abzuege_lfd_l",
        "label": "LSt – St.-Abzüge lfd. (L)",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "2.498,25",
        "x0": 184.92, "top": 552.28,
        "x1": 216.03, "bottom": 560.27,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "steuerrechtl_abzuege_gesamt",
        "label": "Steuerrechtl. Abzüge gesamt",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "2.597,70",
        "x0": 536.39, "top": 552.28,
        "x1": 567.5, "bottom": 560.27,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "solz_st_brutto_lfd_l",
        "label": "SolZ – St.-Brutto lfd. (L)",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "9.582,19",
        "x0": 116.9, "top": 561.35,
        "x1": 148.01, "bottom": 569.34,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "solz_betrag",
        "label": "SolZ – Betrag",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "99,45",
        "x0": 196.03, "top": 561.35,
        "x1": 216.03, "bottom": 569.34,
        "alignment": "right",
        "type": "number",
    },
    # SolZ row label
    {
        "id": "solz_label",
        "label": "SolZ (Zeile)",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "",
        "x0": 59.53, "top": 561.22,
        "x1": 73.87, "bottom": 568.19,
        "alignment": "left",
        "type": "text",
        "font_size": 6.97,
        "editable": False,
    },
    # KiSt row label + value fields
    {
        "id": "kist_label",
        "label": "KiSt (Zeile)",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "",
        "x0": 59.53, "top": 570.29,
        "x1": 72.32, "bottom": 577.26,
        "alignment": "left",
        "type": "text",
        "font_size": 6.97,
        "editable": False,
    },
    {
        "id": "kist_st_brutto_lfd_l",
        "label": "KiSt – St.-Brutto lfd. (L)",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "",
        "x0": 116.9, "top": 570.29,
        "x1": 148.01, "bottom": 577.26,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "kist_betrag",
        "label": "KiSt – Betrag",
        "section": "STEUER-ABRECHNUNG",
        "default_value": "",
        "x0": 196.03, "top": 570.29,
        "x1": 216.03, "bottom": 577.26,
        "alignment": "right",
        "type": "number",
    },

    # ── SV-ABRECHNUNG ─────────────────────────────────────────────────
    # SV row labels (6.97pt font)
    {
        "id": "kv_label",
        "label": "KV (Zeile)",
        "section": "SV-ABRECHNUNG",
        "default_value": "",
        "x0": 62.36, "top": 588.43,
        "x1": 71.67, "bottom": 595.40,
        "alignment": "left",
        "type": "text",
        "font_size": 6.97,
        "editable": False,
    },

    {
        "id": "kv_sv_brutto_lfd",
        "label": "KV – SV-Brutto lfd.",
        "section": "SV-ABRECHNUNG",
        "default_value": "5.512,50",
        "x0": 150.91, "top": 588.56,
        "x1": 182.02, "bottom": 596.55,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "kv_sv_beitrag_lfd",
        "label": "KV – SV-Beitrag lfd.",
        "section": "SV-ABRECHNUNG",
        "default_value": "498,88",
        "x0": 259.61, "top": 588.56,
        "x1": 284.05, "bottom": 596.55,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "sv_rechtl_abzuege_gesamt",
        "label": "SV-rechtl. Abzüge gesamt",
        "section": "SV-ABRECHNUNG",
        "default_value": "1.484,49",
        "x0": 536.39, "top": 588.56,
        "x1": 567.49, "bottom": 596.55,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "rv_sv_brutto_lfd",
        "label": "RV – SV-Brutto lfd.",
        "section": "SV-ABRECHNUNG",
        "default_value": "8.050,00",
        "x0": 150.91, "top": 597.63,
        "x1": 182.02, "bottom": 605.62,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "rv_sv_beitrag_lfd",
        "label": "RV – SV-Beitrag lfd.",
        "section": "SV-ABRECHNUNG",
        "default_value": "748,65",
        "x0": 259.61, "top": 597.63,
        "x1": 284.05, "bottom": 605.62,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "rv_label",
        "label": "RV (Zeile)",
        "section": "SV-ABRECHNUNG",
        "default_value": "",
        "x0": 62.36, "top": 597.50,
        "x1": 72.05, "bottom": 604.47,
        "alignment": "left",
        "type": "text",
        "font_size": 6.97,
        "editable": False,
    },
    {
        "id": "av_sv_brutto_lfd",
        "label": "AV – SV-Brutto lfd.",
        "section": "SV-ABRECHNUNG",
        "default_value": "8.050,00",
        "x0": 150.91, "top": 606.7,
        "x1": 182.02, "bottom": 614.69,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "av_sv_beitrag_lfd",
        "label": "AV – SV-Beitrag lfd.",
        "section": "SV-ABRECHNUNG",
        "default_value": "104,65",
        "x0": 259.61, "top": 606.7,
        "x1": 284.05, "bottom": 614.69,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "av_label",
        "label": "AV (Zeile)",
        "section": "SV-ABRECHNUNG",
        "default_value": "",
        "x0": 62.36, "top": 606.57,
        "x1": 71.67, "bottom": 613.54,
        "alignment": "left",
        "type": "text",
        "font_size": 6.97,
        "editable": False,
    },
    {
        "id": "pv_sv_brutto_lfd",
        "label": "PV – SV-Brutto lfd.",
        "section": "SV-ABRECHNUNG",
        "default_value": "5.512,50",
        "x0": 150.91, "top": 615.77,
        "x1": 182.02, "bottom": 623.76,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "pv_label",
        "label": "PV (Zeile)",
        "section": "SV-ABRECHNUNG",
        "default_value": "",
        "x0": 62.36, "top": 615.64,
        "x1": 71.67, "bottom": 622.61,
        "alignment": "left",
        "type": "text",
        "font_size": 6.97,
        "editable": False,
    },
    {
        "id": "pv_kinder_kennzeichen",
        "label": "PV – Kinder-Kennzeichen",
        "section": "SV-ABRECHNUNG",
        "default_value": "0",
        "x0": 221.68, "top": 615.77,
        "x1": 226.13, "bottom": 623.76,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "pv_sv_beitrag_lfd",
        "label": "PV – SV-Beitrag lfd.",
        "section": "SV-ABRECHNUNG",
        "default_value": "132,31",
        "x0": 259.61, "top": 615.77,
        "x1": 284.05, "bottom": 623.76,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "abrechnungs_netto",
        "label": "Abrechnungs-Netto",
        "section": "SV-ABRECHNUNG",
        "default_value": "5.500,00",
        "x0": 536.39, "top": 633.91,
        "x1": 567.49, "bottom": 641.9,
        "alignment": "right",
        "type": "text",
    },

    # ── VERDIENSTBESCHEINIGUNG ────────────────────────────────────────

    {
        "id": "abrechnungs_brutto_kum",
        "label": "Abrechnungs-Brutto kum.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "70.082,19",
        "x0": 78.44, "top": 660.84,
        "x1": 113.99, "bottom": 668.83,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "steuer_brutto_kum",
        "label": "Steuer-Brutto kum.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "70.082,19",
        "x0": 149.3, "top": 660.84,
        "x1": 184.85, "bottom": 668.83,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "sv_brutto_kum",
        "label": "SV-Brutto kum.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "68.550,00",
        "x0": 220.16, "top": 660.84,
        "x1": 255.71, "bottom": 668.83,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "gesamt_brutto_mtl",
        "label": "Gesamt-Brutto mtl.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "9.582,19",
        "x0": 82.89, "top": 678.98,
        "x1": 113.99, "bottom": 686.97,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "lohnsteuer_kum",
        "label": "Lohnsteuer kum.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "12.702,51-",
        "x0": 148.87, "top": 678.98,
        "x1": 187.08, "bottom": 686.97,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "kv_beitrag_kum",
        "label": "KV-Beitrag kum.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "5.974,13-",
        "x0": 224.15, "top": 678.98,
        "x1": 257.92, "bottom": 686.97,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "nettoentgelt_mtl",
        "label": "Nettoentgelt mtl.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "5.500,00",
        "x0": 82.89, "top": 697.12,
        "x1": 113.99, "bottom": 705.11,
        "alignment": "right",
        "type": "text",
    },
    {
        "id": "solz_kum",
        "label": "SolZ kum.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "99,45-",
        "x0": 164.4, "top": 697.12,
        "x1": 187.06, "bottom": 705.11,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "rv_beitrag_kum",
        "label": "RV-Beitrag kum.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "6.375,15-",
        "x0": 224.15, "top": 697.12,
        "x1": 257.92, "bottom": 705.11,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "av_beitrag_kum",
        "label": "AV-Beitrag kum.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "891,15-",
        "x0": 230.84, "top": 715.26,
        "x1": 257.94, "bottom": 723.25,
        "alignment": "right",
        "type": "number",
    },
    {
        "id": "pv_beitrag_kum",
        "label": "PV-Beitrag kum.",
        "section": "VERDIENSTBESCHEINIGUNG",
        "default_value": "1.584,31-",
        "x0": 224.15, "top": 733.4,
        "x1": 257.92, "bottom": 741.39,
        "alignment": "right",
        "type": "number",
    },

    # ── NETTO-BEZÜGE / NETTO-ABZÜGE ───────────────────────────────────
    # Each row has 3 editable fields: Lohnart, Bezeichnung, Betrag.
    # All empty by default — user fills in as needed.

    # Row 1
    {"id": "korr_label_01", "label": "Netto-Lohnart 01", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 651.77, "x1": 305.60, "bottom": 659.76,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_01", "label": "Netto-Bezeichnung 01", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 651.77, "x1": 392.29, "bottom": 659.76,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_01", "label": "Netto-Betrag 01", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 651.77, "x1": 567.5, "bottom": 659.76,
     "alignment": "right", "type": "number"},

    # Row 2
    {"id": "korr_label_02", "label": "Netto-Lohnart 02", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 660.84, "x1": 305.60, "bottom": 668.83,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_02", "label": "Netto-Bezeichnung 02", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 660.84, "x1": 392.29, "bottom": 668.83,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_02", "label": "Netto-Betrag 02", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 660.84, "x1": 567.5, "bottom": 668.83,
     "alignment": "right", "type": "number"},

    # Row 3
    {"id": "korr_label_03", "label": "Netto-Lohnart 03", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 669.91, "x1": 305.60, "bottom": 677.90,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_03", "label": "Netto-Bezeichnung 03", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 669.91, "x1": 392.29, "bottom": 677.90,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_03", "label": "Netto-Betrag 03", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 669.91, "x1": 567.5, "bottom": 677.9,
     "alignment": "right", "type": "number"},

    # Row 4
    {"id": "korr_label_04", "label": "Netto-Lohnart 04", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 678.98, "x1": 305.60, "bottom": 686.97,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_04", "label": "Netto-Bezeichnung 04", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 678.98, "x1": 392.29, "bottom": 686.97,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_04", "label": "Netto-Betrag 04", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 678.98, "x1": 567.5, "bottom": 686.97,
     "alignment": "right", "type": "number"},

    # Row 5
    {"id": "korr_label_05", "label": "Netto-Lohnart 05", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 688.05, "x1": 305.60, "bottom": 696.04,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_05", "label": "Netto-Bezeichnung 05", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 688.05, "x1": 392.29, "bottom": 696.04,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_05", "label": "Netto-Betrag 05", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 688.05, "x1": 567.5, "bottom": 696.04,
     "alignment": "right", "type": "number"},

    # Row 6
    {"id": "korr_label_06", "label": "Netto-Lohnart 06", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 697.12, "x1": 305.60, "bottom": 705.11,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_06", "label": "Netto-Bezeichnung 06", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 697.12, "x1": 392.29, "bottom": 705.11,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_06", "label": "Netto-Betrag 06", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 697.12, "x1": 567.5, "bottom": 705.11,
     "alignment": "right", "type": "number"},

    # Row 7
    {"id": "korr_label_07", "label": "Netto-Lohnart 07", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 706.19, "x1": 305.60, "bottom": 714.18,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_07", "label": "Netto-Bezeichnung 07", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 706.19, "x1": 392.29, "bottom": 714.18,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_07", "label": "Netto-Betrag 07", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 706.19, "x1": 567.5, "bottom": 714.18,
     "alignment": "right", "type": "number"},

    # Row 8
    {"id": "korr_label_08", "label": "Netto-Lohnart 08", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 715.26, "x1": 305.60, "bottom": 723.25,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_08", "label": "Netto-Bezeichnung 08", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 715.26, "x1": 392.29, "bottom": 723.25,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_08", "label": "Netto-Betrag 08", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 715.26, "x1": 567.5, "bottom": 723.25,
     "alignment": "right", "type": "number"},

    # Row 9
    {"id": "korr_label_09", "label": "Netto-Lohnart 09", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 724.33, "x1": 305.60, "bottom": 732.32,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_09", "label": "Netto-Bezeichnung 09", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 724.33, "x1": 392.29, "bottom": 732.32,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_09", "label": "Netto-Betrag 09", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 724.33, "x1": 567.5, "bottom": 732.32,
     "alignment": "right", "type": "number"},

    # Row 10
    {"id": "korr_label_10", "label": "Netto-Lohnart 10", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 733.40, "x1": 305.60, "bottom": 741.39,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_10", "label": "Netto-Bezeichnung 10", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 733.40, "x1": 392.29, "bottom": 741.39,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_10", "label": "Netto-Betrag 10", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 733.4, "x1": 567.5, "bottom": 741.39,
     "alignment": "right", "type": "number"},

    # Row 11
    {"id": "korr_label_11", "label": "Netto-Lohnart 11", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 282.51, "top": 742.47, "x1": 305.60, "bottom": 750.46,
     "alignment": "left", "type": "text"},
    {"id": "korr_desc_11", "label": "Netto-Bezeichnung 11", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 313.21, "top": 742.47, "x1": 392.29, "bottom": 750.46,
     "alignment": "left", "type": "text"},
    {"id": "korr_betrag_11", "label": "Netto-Betrag 11", "section": "NETTO-BEZÜGE/ABZÜGE",
     "default_value": "", "x0": 536.39, "top": 742.47, "x1": 567.5, "bottom": 750.46,
     "alignment": "right", "type": "number"},

    # ── BANKVERBINDUNG & AUSZAHLUNG ───────────────────────────────────

    {
        "id": "bank",
        "label": "Bank",
        "section": "BANKVERBINDUNG & AUSZAHLUNG",
        "default_value": "xxx - xxxxxxxx xxxxxxxxx",
        "x0": 303.29, "top": 752.39,
        "x1": 393.02, "bottom": 760.38,
        "alignment": "left",
        "type": "text",
    },
    {
        "id": "bic",
        "label": "BIC",
        "section": "BANKVERBINDUNG & AUSZAHLUNG",
        "default_value": "xxxxxxxxxxx",
        "x0": 303.29, "top": 761.46,
        "x1": 361.48, "bottom": 769.45,
        "alignment": "left",
        "type": "text",
        "no_length_check": True,
    },
    {
        "id": "iban",
        "label": "IBAN",
        "section": "BANKVERBINDUNG & AUSZAHLUNG",
        "default_value": "xxxx xxxx xxxx xxxx xxxx xx",
        "x0": 303.29, "top": 770.53,
        "x1": 414.38, "bottom": 778.52,
        "alignment": "left",
        "type": "iban",
    },
    {
        "id": "auszahlungsbetrag",
        "label": "Auszahlungsbetrag",
        "section": "BANKVERBINDUNG & AUSZAHLUNG",
        "default_value": "42.455,49",
        "x0": 531.94, "top": 760.89,
        "x1": 567.49, "bottom": 768.88,
        "alignment": "right",
        "type": "number",
    },

    # ── ERSTELLUNGSVERMERK ────────────────────────────────────────────
    # The full line is composed of 8 individual fields.  Only 3 are
    # editable (date, time, company name); the remaining 5 are fixed
    # text fragments that always render as-is.
    #
    # Fixed fields have "editable": False — they are hidden from the
    # form panel but still rendered onto the PDF.

    # Fixed: "Erstellt am"
    {
        "id": "erstellt_prefix",
        "label": "Erstellt am (prefix)",
        "section": "ERSTELLUNGSVERMERK",
        "default_value": "Erstellt am ",
        "x0": 51.02, "top": 780.45,
        "x1": 80.00, "bottom": 786.44,
        "alignment": "left",
        "type": "text",
        "font_size": 5.98,
        "editable": False,
    },
    # Editable: date
    {
        "id": "erstellt_am",
        "label": "Erstellt am (Datum)",
        "section": "ERSTELLUNGSVERMERK",
        "default_value": "16.01.2026 ",
        "x0": 80.94, "top": 780.45,
        "x1": 111.00, "bottom": 786.44,
        "alignment": "left",
        "type": "date",
        "font_size": 5.98,
    },
    # Fixed: "um"
    {
        "id": "erstellt_um_prefix",
        "label": "um (prefix)",
        "section": "ERSTELLUNGSVERMERK",
        "default_value": "um ",
        "x0": 112.53, "top": 780.45,
        "x1": 121.00, "bottom": 786.44,
        "alignment": "left",
        "type": "text",
        "font_size": 5.98,
        "editable": False,
    },
    # Editable: time
    {
        "id": "erstellt_um",
        "label": "Erstellt um (Uhrzeit)",
        "section": "ERSTELLUNGSVERMERK",
        "default_value": "10:16 ",
        "x0": 122.50, "top": 780.45,
        "x1": 138.00, "bottom": 786.44,
        "alignment": "left",
        "type": "text",
        "font_size": 5.98,
    },
    # Fixed: "Uhr von"
    {
        "id": "erstellt_uhr_von",
        "label": "Uhr von (fixed)",
        "section": "ERSTELLUNGSVERMERK",
        "default_value": "Uhr von ",
        "x0": 139.13, "top": 780.45,
        "x1": 161.00, "bottom": 786.44,
        "alignment": "left",
        "type": "text",
        "font_size": 5.98,
        "editable": False,
    },
    # Fixed: device name
    {
        "id": "erstellt_geraet",
        "label": "Gerät (fixed)",
        "section": "ERSTELLUNGSVERMERK",
        "default_value": "Macbook-air-2 ",
        "x0": 161.73, "top": 780.45,
        "x1": 200.00, "bottom": 786.44,
        "alignment": "left",
        "type": "text",
        "font_size": 5.98,
        "editable": False,
    },
    # Fixed: software version
    {
        "id": "erstellt_software",
        "label": "Software (fixed)",
        "section": "ERSTELLUNGSVERMERK",
        "default_value": "mit Agenda LOHN V27.0 R1: ",
        "x0": 201.61, "top": 780.45,
        "x1": 279.00, "bottom": 786.44,
        "alignment": "left",
        "type": "text",
        "font_size": 5.98,
        "editable": False,
    },
    # Editable: company name
    {
        "id": "erstellt_firmenname",
        "label": "Firmenname (Vermerk)",
        "section": "ERSTELLUNGSVERMERK",
        "default_value": "Lohn Bucha",
        "x0": 280.07, "top": 780.45,
        "x1": 420.00, "bottom": 786.44,
        "alignment": "left",
        "type": "text",
        "font_size": 5.98,
    },
]

# ── Convenience lookups ───────────────────────────────────────────────────

FIELDS_BY_ID: dict[str, dict] = {f["id"]: f for f in FIELD_SPEC}

SECTIONS: list[str] = list(dict.fromkeys(f["section"] for f in FIELD_SPEC))

FIELDS_BY_SECTION: dict[str, list[dict]] = {}
for _f in FIELD_SPEC:
    FIELDS_BY_SECTION.setdefault(_f["section"], []).append(_f)


# ── Validation ────────────────────────────────────────────────────────────────

import re as _re

def validate_field(field: dict, value: str) -> str | None:
    """
    Validate *value* for *field*.

    Returns an error message string if invalid, or None if valid.
    """
    if not value or not value.strip():
        return None   # empty is always OK

    fid   = field.get("id", "")
    ftype = field.get("type", "text")

    # ── Per-field custom validators ──────────────────────────────────
    if fid == "pv_kinder_kennzeichen":
        if not _re.match(r"^[0-5]$", value):
            return "Nur 0\u20135 erlaubt"
        return None

    if fid in ("seite_aktuell", "seite_gesamt", "blatt_nummer"):
        if not _re.match(r"^[1-9]\d?$", value):
            return "Nur 1\u201399 erlaubt"
        return None

    if fid in ("kw_zeile_1", "kw_zeile_2", "kw_zeile_3", "kw_zeile_4", "kw_zeile_5"):
        if not _re.match(r"^[1-9]\d?$", value) or int(value) > 53:
            return "Nur 1\u201353 erlaubt"
        return None

    if fid == "erstellt_um":
        if not _re.match(r"^([01]\d|2[0-3]):[0-5]\d$", value):
            return "Format: HH:MM"
        return None

    # ── Generic validators ───────────────────────────────────────────

    # Check if text fits within bounding box width (approximate)
    # Each character ≈ 4.5pt at 7.5pt Helvetica
    # Skip for wrappable fields and fields explicitly marked no_length_check
    # (e.g. address/name fields whose bbox is narrow but values can be longer).
    if not field.get("wrap") and not field.get("no_length_check"):
        max_width = field["x1"] - field["x0"]
        approx_chars = int(max_width / 4.2)
        if len(value) > approx_chars + 3:  # give a little buffer
            return f"Zu lang (max ~{approx_chars} Zeichen)"

    if ftype == "date":
        if not _re.match(r"^\d{2}\.\d{2}\.\d{4}$", value):
            return "Format: TT.MM.JJJJ"

    elif ftype == "number":
        # German number format: optional thousands dot, comma decimal, optional trailing minus
        cleaned = value.replace(" ", "")
        if not _re.match(r"^-?\d{1,3}(\.\d{3})*(,\d{1,2})?-?$", cleaned):
            if not _re.match(r"^\d+(,\d{1,2})?-?$", cleaned):
                return "Zahlenformat: N.NNN,NN oder NNN,NN"

    elif ftype == "iban":
        cleaned = value.replace(" ", "").upper()
        if len(cleaned) < 15 or len(cleaned) > 34 or not cleaned[:2].isalpha():
            return "IBAN: 15-34 Zeichen, beginnt mit Ländercode (z.B. DE, AT, CH)"


    return None
